name: macOS

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: ${{ matrix.build_type }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: >
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} -j

      - name: Test
        run: ./build/zopfli_tests

      - name: Makefile build
        run: make
